# -*- coding: utf-8 -*-
"""Mean_Median_Mode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xPo0QeABxH8Vw6xwrjFiPKGs6WHkdmfK
"""

from statistics import  mode

def calcluate_mean(data):
  mean = sum(data) / len(data)
  return mean
def calcluate_median(data):
  data.sort()
  n =len(data)
  mid = n // 2
  if n % 2 == 0:
    median = (data[mid - 1] + data[mid]) / 2
  else:
    median = data[mid]
  return median

def calculate_mode(data):
    try:
        mode_result = mode(data)
        return mode_result
    except:
        return "No unique mode"


dataset = [10,20,19,200,199,30,32,25,55]
mean_Result = calcluate_mean(dataset)
median = calcluate_median(dataset)
print("Median:", median)
mode_result = calculate_mode(dataset)
print("Mode:", mode_result)
print("Mean:", mean_Result)